name: Train and Evaluate Churn Model

on:
  push:
    branches:
      - main

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Iniciar MLflow en segundo plano
      - name: Start MLflow Server
        run: |
          mlflow server --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0 --port 5000 &
      
      # Paso 5: Esperar a que MLflow esté activo
      - name: Wait for MLflow Server
        run: sleep 10

      # Paso 6: Entrenar el modelo
      - name: Run training script
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: python scripts/train.py

      # Paso 7: Evaluar el modelo
      - name: Run evaluation script
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: python scripts/evaluate.py
